export const FILE_SIZE_LIMIT = 50 * 1024 * 1024; // 50MB

export enum DATABASE_CONSTANT_ID {
  TEACHING_DESCRIPTION = "TEACHING_DESCRIPTION",
  YOUTUBE_URL = "YOUTUBE_URL",
  FACEBOOK_URL = "FACEBOOK_URL",
  ADDRESS_LINE_1 = "ADDRESS_LINE_1",
  ADDRESS_LINE_2 = "ADDRESS_LINE_2",
  PHONE_NUMBER = "PHONE_NUMBER",
  CLUB_ID = "CLUB_ID",
  CONTACT_EMAIL = "CONTACT_EMAIL"
}
